set(CMAKE_SYSTEM_NAME                   Generic)
set(CMAKE_SYSTEM_PROCESSOR              arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE       STATIC_LIBRARY)

if (WIN32)
  set(EXE_SUFFIX ".exe")
  cmake_path(SET USER_DIR "$ENV{USERPROFILE}" NORMALIZE)
else()
  set(EXE_SUFFIX "")
  cmake_path(SET USER_DIR "$ENV{HOME}" NORMALIZE)
endif ()

# This file is autogenerated by SLC and provides any system defaults.
# Users can manually override any toolchain path using the environment
# variables defined below or by manually changing this file.
set(AUTOGEN_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/autogen_toolchain.cmake")
if (EXISTS "${AUTOGEN_TOOLCHAIN_FILE}")
include("${AUTOGEN_TOOLCHAIN_FILE}")
endif ()

if (DEFINED ENV{ARM_GCC_DIR})
  set(TOOLCHAIN_DIR "$ENV{ARM_GCC_DIR}/bin/")
elseif (DEFAULT_TOOLCHAIN_DIR)
  set(TOOLCHAIN_DIR ${DEFAULT_TOOLCHAIN_DIR})
endif ()

if (DEFINED ENV{POST_BUILD_EXE})
  set(POST_BUILD_EXE "$ENV{POST_BUILD_EXE}")
elseif (DEFAULT_POST_BUILD_EXE)
  set(POST_BUILD_EXE ${DEFAULT_POST_BUILD_EXE})
endif ()

if (DEFINED ENV{NINJA_EXE_PATH})
  set(NINJA_RUNTIME_PATH "$ENV{NINJA_EXE_PATH}")
elseif (DEFAULT_NINJA_RUNTIME_PATH)
  set(NINJA_RUNTIME_PATH ${DEFAULT_NINJA_RUNTIME_PATH})
endif ()

# Use default lookup mechanisms if the OS specific values are not set above
if (NINJA_RUNTIME_PATH)
  set(CMAKE_MAKE_PROGRAM ${NINJA_RUNTIME_PATH} CACHE FILEPATH "" FORCE)
else()
  # This is just to check that ninja is found somewhere so that we can present a
  # nicer error message if it's not.
  find_program(SYSTEM_NINJA NAMES ninja ninja-build)
  if (EXISTS "${SYSTEM_NINJA}")
    set(NINJA_RUNTIME_PATH ${SYSTEM_NINJA})
  endif ()
endif ()

if (NOT DEFINED TOOLCHAIN_DIR OR NOT DEFINED POST_BUILD_EXE OR NOT DEFINED NINJA_RUNTIME_PATH)
  message(FATAL_ERROR
    "\n"
    "The required Toolchain, Post-build, or Ninja runtime paths are not set.\n"
    "Please either set the environment variable overrides or regenerate the project using"
    "'slc generate' or by regenerating from Simplicity Studio to ensure"
    "the autogen_toolchain.cmake file is present.\n"
    "Found:\n"
    " TOOLCHAIN_DIR=${TOOLCHAIN_DIR}\n"
    " POST_BUILD_EXE=${POST_BUILD_EXE}\n"
    " NINJA_RUNTIME_PATH=${NINJA_RUNTIME_PATH}"
    )
endif ()

set(TARGET_TRIPLET "arm-none-eabi-")
set(CMAKE_C_COMPILER    ${TOOLCHAIN_DIR}${TARGET_TRIPLET}gcc${EXE_SUFFIX})
set(CMAKE_CXX_COMPILER  ${TOOLCHAIN_DIR}${TARGET_TRIPLET}g++${EXE_SUFFIX})
set(CMAKE_ASM_COMPILER  ${TOOLCHAIN_DIR}${TARGET_TRIPLET}gcc${EXE_SUFFIX})
set(CMAKE_LINKER        ${TOOLCHAIN_DIR}${TARGET_TRIPLET}gcc${EXE_SUFFIX})
set(CMAKE_AR            ${TOOLCHAIN_DIR}${TARGET_TRIPLET}ar${EXE_SUFFIX})
set(CMAKE_SIZE_UTIL     ${TOOLCHAIN_DIR}${TARGET_TRIPLET}size${EXE_SUFFIX})
set(CMAKE_STRIP         ${TOOLCHAIN_DIR}${TARGET_TRIPLET}strip${EXE_SUFFIX})
set(CMAKE_OBJCOPY       ${TOOLCHAIN_DIR}${TARGET_TRIPLET}objcopy${EXE_SUFFIX})
set(CMAKE_OBJDUMP       ${TOOLCHAIN_DIR}${TARGET_TRIPLET}objdump${EXE_SUFFIX})
set(CMAKE_NM_UTIL       ${TOOLCHAIN_DIR}${TARGET_TRIPLET}gcc-nm${EXE_SUFFIX})
set(CMAKE_RANLIB        ${TOOLCHAIN_DIR}${TARGET_TRIPLET}gcc-ranlib${EXE_SUFFIX})
set(CMAKE_GCOV          ${TOOLCHAIN_DIR}${TARGET_TRIPLET}gcov${EXE_SUFFIX})

set(OBJCOPY_SREC_CMD    "-O;srec")
set(OBJCOPY_IHEX_CMD    "-O;ihex")
set(OBJCOPY_BIN_CMD     "-O;binary")

set(CMAKE_C_STANDARD_REQUIRED   OFF)
set(CMAKE_CXX_STANDARD_REQUIRED OFF)
set(CMAKE_C_EXTENSIONS          OFF)

set(CMAKE_C_FLAGS_RELEASE               "" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELEASE             "" CACHE STRING "")

# Response file support
SET(CMAKE_C_USE_RESPONSE_FILE_FOR_OBJECTS   1)
SET(CMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS 1)
SET(CMAKE_C_RESPONSE_FILE_LINK_FLAG         "@")
SET(CMAKE_CXX_RESPONSE_FILE_LINK_FLAG       "@")
SET(CMAKE_NINJA_FORCE_RESPONSE_FILE         1 CACHE INTERNAL "")


set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM   NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY   ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE   ONLY)

set(CMAKE_EXECUTABLE_SUFFIX     .out)
set(CMAKE_EXECUTABLE_SUFFIX_C   .out)
set(CMAKE_EXECUTABLE_SUFFIX_CXX .out)
